project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - scripts/index.qmd
    - scripts/glossary.qmd
website:
  title: ""
  page-navigation: true
  navbar:
    search: true
    pinned: true
    left:
      - text: "Federal Recovery Funds Dashboard"
        href: scripts/index.qmd
      - href: scripts/glossary.qmd
  sidebar:
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - scripts/index.qmd
format:
  html:
    page-layout: full
    theme:
      - styles.scss
    mainfont: montserrat
    embed-resources: true
    code-fold: false
    code-link: true
    code-line-numbers: true
    df-print: default
    toc: true
    toc-title: Contents
    toc-depth: 3
    toc-location: left
    highlight-style: github
    smooth-scroll: true
execute:
  freeze: auto
  echo: false
  message: false
  warning: false
  error: false
