project:
  type: website
  render:
    - index.qmd
    - glossary.qmd
website:
  title: ""
  page-navigation: true
  navbar:
    search: true
    pinned: true
    left:
      - text: "Federal Recovery Funds Dashboard"
        href: index.qmd
      - href: glossary.qmd
format:
  html:
    # include-in-header: header.html
    css: style.css
    # theme:
    #   - styles.scss
    # mainfont: montserrat
    embed-resources: true
    code-fold: false
    code-link: true
    code-line-numbers: true
    df-print: default
    toc: false
    toc-title: Contents
    toc-depth: 3
    toc-location: left
    highlight-style: pygments
    smooth-scroll: true
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 250px
      gutter-width: 1.5em
execute:
  freeze: auto
  echo: false
  message: false
  warning: false
  error: false
