project:
  type: website
  render:
    - index.qmd
    - glossary.qmd
website:
  title: ""
  page-navigation: true
  navbar:
    search: true
    pinned: true
    left:
      - text: "Home"
        href: _site/index.html
      - href: _site/glossary.html
format:
  html:
    include-in-header: header.html
    css: style.css
    embed-resources: true
    standalone: true
    code-fold: true
    code-link: true
    code-line-numbers: true
    df-print: default
    toc: false
    toc-depth: 3
    number-sections: false
    number-depth: 3
    highlight-style: pygments
    smooth-scroll: true
