---
title: ""
---

# Glossary

```{r, echo = FALSE}
cur_date <- Sys.Date()
```

<center>**Last Updated:** `r cur_date`</center>
<br><br>

*This glossary provides the definition of key terms as used in the Dashboard.*


**Affordable Housing**: investments aimed at preserving or creating affordable
housing units.

**Alternative Emergency Response**: services such as sobering centers, behavior
health programs, and implementation of the 211 call line, a referral line for
human and social services.

**Airports**: defined in the law as any area of land or water used or intended
for landing or takeoff of aircraft including appurtenant area used or intended
for airport buildings, facilities, as well as rights of way together with the
buildings and facilities.

**American Rescue Plan Act (ARPA)**: a \$1.9 trillion economic stimulus bill
addressing economic recovery from the COVID-19 pandemic passed on March 11,
2021. ARPA includes the Coronavirus State and Local Fiscal Recovery Funds
(SLFRF) program, which directed \$350 billion of flexible funds to states,
counties, tribal governments and localities.

**Appropriations**: the amount of funding committed by the federal government to
the city, county, or state for a given program.

**Assistance for Returning Residents/Justice Involved People**: services aimed
at assisting people returning from incarceration or who are involved in the
criminal justice system.

**Assistance for Specific Populations**: targeted programs for specific
populations, such as older adults, veterans, people with disabilities, or people
experiencing homelessness.

**Awards**: financial assistance that provides support or stimulation to
accomplish a public purpose. Awards include grants and other agreements in the
form of money or property in lieu of money, by the federal government to an
eligible recipient.

**Community Development**: investments aimed at developing or maintaining
community vibrancy.

**Community Investment**: programs that address a community's collective needs,
and engage the community in developing sustainable solutions toward communal
challenges. Programs include infrastructure support, small business and economic
support, and education and health services.

**Community Safety**: programs and initiatives that seek to prevent or reduce
violence, assist people in reintegrating into their community following
incarceration or while they are involved in the criminal legal system, aid
people who have been the victims of violence, and implement alternative
emergency response services.

**Competitive Grant**: also known as "discretionary" funding, this type of grant
is awarded based on a competitive process, which includes proposal selection
based on a single reviewer or a team of reviewers. Financing of this type is
determined by the merits of the application and is not predetermined.

**Consolidated Appropriations Act 2021**: A \$2.3 trillion spending bill passed
on December 21, 2020, that includes the Coronavirus Response and Relief
Supplemental Appropriations Act (CRRSAA), which provided additional stimulus
relief for the COVID-19 pandemic.

**Coronavirus Aid, Relief, and Economic Security Act (CARES)**: a \$2.2 trillion
economic stimulus bill addressing economic recovery from the COVID-19 pandemic
passed on March 27, 2020. The CARES Act included direct cash payments to
individuals, expanded unemployment benefits, and business assistance funds.

**Criminal Justice Reform**: programs that address structural issues in criminal
justice systems, such as youth diversion programs and revisions to budgets and
case management.

**Direct Cash Assistance**: unrestricted cash flowing directly to individuals
and families.

**Earmarks**: funds provided by Congress for specific projects, not to be
allocated by federal agencies through a competitive process.

**Electric Vehicle Infrastructure**: equipment that supports the use of electric
vehicles, such as battery charging stations and rapid charging stations.

**Employment Opportunities**: funding allocations that will result in job
creation.

**Expiration**: the date at which funds are no longer available for expenditure.
Expiration dates vary by program.

**Formula Grant**: Unlike a competitive grant, formula grants are awarded to
recipients who are predetermined, and the term "formula" refers to the way the
grant funding is allocated to recipients. Formula grants are non-competitive.
Legislation and regulations set the formula for this type of funding, so funders
must adhere to that formula when awarding grants. Normally, the funds from
formula grants are awarded among the States by a specific formula. Next, the
choices of which projects to support are made on the local level and funding is
recurring. All eligible applicants who meet the minimum requirements stated in
the application process are entitled to receive funding.

**General Fiscal Support**: flexible funds available for broad COVID-19 economic
recovery efforts.

**Homeowners Assistance**: programs that support property owners in maintaining
their homeowner status and that help non-homeowners to pursue ownership.

**Homelessness Supports/Prevention**: programs and wraparound supports for
people experiencing or at risk of experiencing homelessness.

**Household Investment**: programs that provide targeted support for households,
such as direct cash assistance and legal services, and expanding awareness of
and access to public services.

**Household Supportive Services**: services aimed at addressing household
stability, such as unemployment insurance, energy affordability assistance, and
early education assistance.

**Housing**: programs addressing a range of needs for renters, homeowners,
people experiencing homelessness, including affordability, stability, shelter
solutions, and temporary and permanent supportive housing services.

**Infrastructure**: programs that support organizational structures and
facilities, such as buildings, roads, highways, and bridges.

**Infrastructure Investment and Jobs Act (also known as the Bipartisan
Infrastructure Law)**: a federal act to authorize \$1.2 trillion in funds for
Federal-aid highways, highway safety programs, transit programs, climate
resilience, and other purposes through September 30th, 2026.

**Job Training**: programs aimed at equipping people with necessary skills to
obtain and maintain jobs in specific industries.

**Rail**: rail infrastructure includes tracks, other infrastructure surrounding
tracks, tunnels, bridges, stations and terminals, platforms, train control and
signaling systems, and associated machinery and equipment.

**Rebate**: funds paid by the federal government to pay back eligible recipients
for allowable expenditures.

**Renter Assistance**: programs supporting people and households living in
rental housing.

**Revolving Loan Fund**: a pool of money that uses interest and principal
payments on old loans to issue new loans.

**Roads, Bridges, and Major Projects**: \$110B allocated through IIJA that
includes the Surface Transportation Reauthorization Act and Surface
Transportation Investment Act, which funds new, dedicated grant program to
replace and repair bridges and increases funding for the major project
competitive grant programs. At the same time, the package preserves the 90/10
split of federal highway aid to states.

**Small Business**: programs that support small businesses in maintaining and
expanding operations.

**Traffic Safety**: programs that protect pedestrians, cyclists, motorists,
vehicle passengers, and other passengers of on-road public transport.

**Transit and Transportation**: programs that support transit systems and the
infrastructure which support them, including vehicles, busses, trains, bicycles,
and pedestrian walkways.

**Utility Assistance**: assistance to households to cover utility costs,
including water.

**Victim Support Services**: services and supports for victims of violent crime
and their families, including mental health supports, crisis intervention,
support with accessing crime victim compensation, housing, and food.

**Violence Prevention/Reduction**: funding aimed at preventing or reducing
violence, including for violence intervention programming and for community
groups.

**Water Infrastructure**: all man-made and natural features that move and treat
water, including drinking water, wastewater, and stormwater infrastructure.

**Workforce Supportive Services**: programs which connect people to employment
opportunities.

**Workforce Sustainability**: assistance to maintain existing workforce.

